### ISSUE TITLE
RSS feed link not working

### ISSUE THREAD

**Issue by eahlberg** [lazamar/lazamar.github.io#1]
Hey! Thanks for a really interesting and inspiring write-up about Huffman codes. When I tried to subscribe to the RSS feed, I noticed that the link was broken.

PS.
Thanks for `nix-versions` as well, it's saved me tons of time!

**Comment by lazamar** [comment]
Thanks for reporting it! I'll have a look and make sure it's working.

**Comment by lazamar** [comment]
The link in the website's footer was broken. The right one is [this one](https://lazamar.github.io/feed.xml). The website is fixed now too.
Tell me if that works for you.

**Comment by eahlberg** [comment]
Cool, works great! 🙏
